Move setup.py configs to pyproject.toml

diff --git a/.github/workflows/main-build-and-publish.yml b/.github/workflows/main-build-and-publish.yml
--- a/.github/workflows/main-build-and-publish.yml
+++ b/.github/workflows/main-build-and-publish.yml
@@ -31,8 +31,7 @@ jobs:
           pip install .[all]
           pip uninstall -y hello-world-api-py
           pip freeze > requirements.txt
-          git diff --quiet
-          if [ ! $? -eq 0 ]; then
+          if ! `git diff --quiet`; then
             echo "pip freeze caused file changes, failing!"
             exit 1
           fi
@@ -41,6 +40,10 @@ jobs:
         run: |
           source venv/bin/activate
           make style
+          if ! `git diff --quiet`; then
+            echo "make style caused file changes, failing!"
+            exit 1
+          fi
 
       - name: Run tests
         run: |
